# Generated by Django 5.0 on 2023-12-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Sports', models.CharField(max_length=100)),
                ('Hobbies', models.CharField(max_length=100)),
            ],
        ),
    ]
