# Generated by Django 5.0 on 2023-12-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_name_studyprogram_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='first_name',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
