# Generated by Django 5.0 on 2023-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_studyprogram_age_alter_studyprogram_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='passwd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
