# Generated by Django 5.0 on 2023-12-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_studyprogram_email_studyprogram_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='last_name',
        ),
    ]
